### ISSUE TITLE
When X number of videos are added to placeholder, all videos go blank

### ISSUE THREAD

**Issue by AlexKolenoff** [Rise-Vision/widget-video#38] opened 2015-05-27 16:32 UTC
Complete the steps below using Rise Player on Win7

1. Create a new presentation. 
2. Add a placeholder
3. Add three instances of the Video Widget where each video is unique webm video and configured for PUD
4. Run the Presentation on Win7 with Rise Player
5. Once the Presentation is running, start adding additional videos, one at a time (e.g., add the video, publish, repeat), each video should be unique, webm and configured for PUD.

When you have a between 8-12 videos total in the Playlist, all instances of the Video Widget will fail and stop playing.

From what I can tell, the size of the video did not impact the issue occurring.  There are no network or page errors in dev tools. If you remove the last video you added, the videos will begin to play again. 

Presentation: http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=6a245ce4-f133-4813-8d85-9f8d5103cdbc?cid=cd7cb86b-8134-4c41-996c-d1ca82e5a1a9

OS:
Windows 7, Ubuntu 14.04

Chrome Ver:
43.0.2357.81 (CAP version 1.24.30)

**Comment by AlexKolenoff** [comment] 2015-05-27 16:32
@alanclayton @btfrise FYI

**Comment by alanclayton** [comment] 2015-05-27 17:36
@AlexKolenoff @btfrise This is really confusing. My interpretation of the issue is as follows, let me know if it is correct.

If you have 3 webm vidoes in a playlist, regardless of size, with PUD enabled, running Chrome App Player on Win7, all instances of the Widget (one per webm video) will stop playing if you continue to add additional webm videos to the playlist with PUD enabled, one-by-one (e.g., add a new video, publish, repeat). 

The number of videos you add to the playlist to recreate this issue is inconsistent, but seems to occur when when you approach a total of 8 webm videos in the playlist. Once this issue occurs, videos will resume playing if you remove the last video you added to the Playlist. 

Is that correct? When you add additional videos are they the same as what you already have in the playlist? What errors do you see in Console? Are there any errors in Network? Does the issue only occur when PUD is enabled? Is this only occurring on Win 7? 

Can you clarify on step 4. Why do you need to reboot? Shouldn't the Presentation update to reflect your changes once you've published? 

Last, this behavior of adding and removing videos at such a high rate seems a bit erratic. How common of a use case is this? If this is a common use case, can you describe what the use case is? 



Last, you state that you are unable to verify if file size is a variable in the issue. if that is correct, why does your last step state to test with different size videos? Are you thinking that somebody else will be able to make a correlation between video size and the issue you describe?

**Comment by AlexKolenoff** [comment] 2015-05-27 18:52
@alanclayton 

1) Re your first paragraph/interpretation, correct.  I have specified 3 to start out with because I have not seen an issue with only 3 videos.  One of the tests I did with only 3 videos included a 200 MB video just so I could determine that size was not the issue, and it was not, so I settled on 3 as a starting point.

2) For this issue to happen, you do not *have* to add them one by one, and that doesn't reflect a use case.  This was included in the steps because it helps to determine at what point the issue occurs, since it is inconsistent and depends on the number and combination of videos.

3) Re your second paragraph, I have seen this issue occur with as little as 6 videos.  Yes, I can "fix" it by removing the last video, or removing a different video in the list.

4) Re your third paragraph, to reproduce I am doing so with unique videos.  As a side note, I did later try copies of videos just to see if there was a difference, and there was not.

5) I don't notice anything different in console than what I am accustomed to seeing when things play properly, and no network errors.

6) I did one test with all videos having PUD unchecked and duration specified and it didn't make a difference, the issue still occurs.

7) Matthew took a copy of my presentation and also had issues on Linux.

8) Re step 4 - the reason I specified rebooting in between was to be sure that the behaviour you are seeing on the display while testing, can be confirmed to still occur after a reboot.

9) Re your last paragraph, it seemed to me that there might be a correlation between the issue and the number of videos in combination with video size, but so far I have not been able to prove it definitively.  I was able to add many more "small" videos (5 MB and under) to a Placeholder in one test than I was in another test that included some larger videos, but when I calculated file sizes/total it wasn't consistent.

**Comment by alanclayton** [comment] 2015-05-27 19:14
@AlexKolenoff I updated the steps to recreate. Please review and confirm if I missed anything.

When the issue occurred what did memory usage look like?

**Comment by AlexKolenoff** [comment] 2015-05-27 19:37
@alanclayton Memory usage doesn't look unusual.

You removed mention of this, which might be relevant:

"2) Occasionally the behaviour may be a black screen with an arrow and video controls at the bottom, eg http://screencast.com/t/Gukg1A9Y8BDZ"

**Comment by stulees** [comment] 2015-06-10 15:36
@AlexKolenoff @alanclayton I have been able to replicate the issue, but I am struggling to isolate what is causing this. As Alex mentioned, there are no unusual errors when inspecting console and when I inspect the markup, everything is as it should be. 

Is there any cap to the amount Rise Cache downloads/caches? Could this possibly be related to this issue - https://github.com/Rise-Vision/player-chromeapp/issues/46 ?

**Comment by AlexKolenoff** [comment] 2015-06-10 16:12
@stulees I was wondering about any cap as well but I don't know.  But this issue doesn't happen with the Video item and that uses Rise cache too.

Unfortunately it's not a matter of the drive being filled up in my tests, I know to check for that because I have seen it happen with clients in the past with videos.

**Comment by AlexKolenoff** [comment] 2015-07-20 17:29
@stulees I think I may be seeing this issue occurring with another client (they have a long list of videos which never play, but when I remove some from the list videos begin playing again).  It looks like this bug is still open but is referenced on the link above, but I am not clear whether this is supposed to be outstanding still or not.  Could you please let me know?

**Comment by stulees** [comment] 2015-07-20 17:31
@AlexKolenoff This fix has not been pushed yet, I'm awaiting approval for doing so.

**Comment by AlexKolenoff** [comment] 2015-07-20 17:53
@stulees Thanks, do you know who is supposed to approve it so I can find out when that will happen?

**Comment by stulees** [comment] 2015-07-20 18:05
@AlexKolenoff Will be @alanclayton and @btfrise , thanks

**Comment by stulees** [comment] 2015-07-21 13:15
@AlexKolenoff The fix has now been deployed, thanks

**Comment by stulees** [comment] 2015-07-29 18:15
@AlexKolenoff FYI closing this issue now as its been fixed and deployed.

**Closed by stulees** 2015-07-29 18:15 UTC
Labels: bug
