### ISSUE TITLE
Video folder stops playing after a while

### ISSUE THREAD

**Issue by andrecardoso** [Rise-Vision/widget-video#247] opened 2018-10-15 14:22 UTC
- Operating System Version: Chrome OS

##### What is the expected behavior?

Videos will continue playing

##### What is the actual behavior?

Videos stop playing after a day

##### What steps can be taken to replicate the problem? 

1. Video widget is configured to a video folder with more than 10 files
1. Start player and wait one day
1. Videos stop playing and black screen is shown with the play button in the upper left corner

**Comment by santiagonoguez** [comment] 2018-10-16 16:35
Instead of waiting one day, the problem is easier to replicate by saving the schedule. 
And it's sometimes reproducible also in Player Electron.

Still investigating this.

**Comment by santiagonoguez** [comment] 2018-10-18 15:53
@andrecardoso the fix is now deployed and in master branch, I'll be leaving my chromebit running 24 hours as an extra validation. I'm closing the issue for the time being.

**Closed by santiagonoguez** 2018-10-18 15:53 UTC
